/* 
   Copyright 2013 KLab Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
class Program;

namespace EnginePrototype {
    class _Delegate_Base_FunctionPointerV_inner0;
    template <class TClass> class _DelegateI_FunctionPointerV_inner0;
    class _DelegateS_FunctionPointerV_inner0;
    class _Delegate_Base_FunctionPointerII_inner1;
    template <class TClass> class _DelegateI_FunctionPointerII_inner1;
    class _DelegateS_FunctionPointerII_inner1;
    class _Delegate_Base_FunctionPointerIII_inner2;
    template <class TClass> class _DelegateI_FunctionPointerIII_inner2;
    class _DelegateS_FunctionPointerIII_inner2;
    class _Delegate_Base_FunctionPointerIIII_inner3;
    template <class TClass> class _DelegateI_FunctionPointerIIII_inner3;
    class _DelegateS_FunctionPointerIIII_inner3;
    class _Delegate_Base_FunctionPointerS_inner4;
    template <class TClass> class _DelegateI_FunctionPointerS_inner4;
    class _DelegateS_FunctionPointerS_inner4;
    class _Delegate_Base_FunctionPointerSII_inner5;
    template <class TClass> class _DelegateI_FunctionPointerSII_inner5;
    class _DelegateS_FunctionPointerSII_inner5;
    class _Delegate_Base_FunctionPointerSU_inner6;
    template <class TClass> class _DelegateI_FunctionPointerSU_inner6;
    class _DelegateS_FunctionPointerSU_inner6;
    class _Delegate_Base_FunctionPointerSS_inner7;
    template <class TClass> class _DelegateI_FunctionPointerSS_inner7;
    class _DelegateS_FunctionPointerSS_inner7;
    class _Delegate_Base_FunctionPointerUS_inner8;
    template <class TClass> class _DelegateI_FunctionPointerUS_inner8;
    class _DelegateS_FunctionPointerUS_inner8;
    class _Delegate_Base_FunctionPointerUSS_inner9;
    template <class TClass> class _DelegateI_FunctionPointerUSS_inner9;
    class _DelegateS_FunctionPointerUSS_inner9;
    class _Delegate_Base_FunctionPointerU_inner10;
    template <class TClass> class _DelegateI_FunctionPointerU_inner10;
    class _DelegateS_FunctionPointerU_inner10;
    class _Delegate_Base_FunctionPointerUU_inner11;
    template <class TClass> class _DelegateI_FunctionPointerUU_inner11;
    class _DelegateS_FunctionPointerUU_inner11;
    class _Delegate_Base_FunctionPointerUFF_inner12;
    template <class TClass> class _DelegateI_FunctionPointerUFF_inner12;
    class _DelegateS_FunctionPointerUFF_inner12;
    class _Delegate_Base_FunctionPointerUI_inner13;
    template <class TClass> class _DelegateI_FunctionPointerUI_inner13;
    class _DelegateS_FunctionPointerUI_inner13;
    class _Delegate_Base_FunctionPointerUII_inner14;
    template <class TClass> class _DelegateI_FunctionPointerUII_inner14;
    class _DelegateS_FunctionPointerUII_inner14;
    class _Delegate_Base_FunctionPointerUIIII_inner15;
    template <class TClass> class _DelegateI_FunctionPointerUIIII_inner15;
    class _DelegateS_FunctionPointerUIIII_inner15;
    class _Delegate_Base_FunctionPointerUIIUU_inner16;
    template <class TClass> class _DelegateI_FunctionPointerUIIUU_inner16;
    class _DelegateS_FunctionPointerUIIUU_inner16;
    class _Delegate_Base_FunctionPointerUUII_inner17;
    template <class TClass> class _DelegateI_FunctionPointerUUII_inner17;
    class _DelegateS_FunctionPointerUUII_inner17;
    class _Delegate_Base_FunctionPointerUUUII_inner18;
    template <class TClass> class _DelegateI_FunctionPointerUUUII_inner18;
    class _DelegateS_FunctionPointerUUUII_inner18;
    class _Delegate_Base_FunctionPointerIIIP_retB_inner19;
    template <class TClass> class _DelegateI_FunctionPointerIIIP_retB_inner19;
    class _DelegateS_FunctionPointerIIIP_retB_inner19;
    class _Delegate_Base_FunctionPointerFS_inner20;
    template <class TClass> class _DelegateI_FunctionPointerFS_inner20;
    class _DelegateS_FunctionPointerFS_inner20;
    class _Delegate_Base_CallBack_inner21;
    template <class TClass> class _DelegateI_CallBack_inner21;
    class _DelegateS_CallBack_inner21;
    class _Delegate_Base_ExecuteCallBack_inner22;
    template <class TClass> class _DelegateI_ExecuteCallBack_inner22;
    class _DelegateS_ExecuteCallBack_inner22;
    class _Delegate_Base_DieCallBack_inner23;
    template <class TClass> class _DelegateI_DieCallBack_inner23;
    class _DelegateS_DieCallBack_inner23;
    class _Delegate_Base_CallBack_inner24;
    template <class TClass> class _DelegateI_CallBack_inner24;
    class _DelegateS_CallBack_inner24;
    class _Delegate_Base_CallBack_inner25;
    template <class TClass> class _DelegateI_CallBack_inner25;
    class _DelegateS_CallBack_inner25;
    class _Delegate_Base_CallBackVersionUp_inner26;
    template <class TClass> class _DelegateI_CallBackVersionUp_inner26;
    class _DelegateS_CallBackVersionUp_inner26;
    class _Delegate_Base_CallBack_inner27;
    template <class TClass> class _DelegateI_CallBack_inner27;
    class _DelegateS_CallBack_inner27;
    class _Delegate_Base_onDieCallBack_inner28;
    template <class TClass> class _DelegateI_onDieCallBack_inner28;
    class _DelegateS_onDieCallBack_inner28;
    class _Delegate_Base_CallBack_inner29;
    template <class TClass> class _DelegateI_CallBack_inner29;
    class _DelegateS_CallBack_inner29;
    class _Delegate_Base_OnClickCallBack_inner30;
    template <class TClass> class _DelegateI_OnClickCallBack_inner30;
    class _DelegateS_OnClickCallBack_inner30;
    class _Delegate_Base_OnDblClickCallBack_inner31;
    template <class TClass> class _DelegateI_OnDblClickCallBack_inner31;
    class _DelegateS_OnDblClickCallBack_inner31;
    class _Delegate_Base_OnDragCallBack_inner32;
    template <class TClass> class _DelegateI_OnDragCallBack_inner32;
    class _DelegateS_OnDragCallBack_inner32;
    class _Delegate_Base_OnPinchCallBack_inner33;
    template <class TClass> class _DelegateI_OnPinchCallBack_inner33;
    class _DelegateS_OnPinchCallBack_inner33;
    class _Delegate_Base_OnLongTapCallBack_inner34;
    template <class TClass> class _DelegateI_OnLongTapCallBack_inner34;
    class _DelegateS_OnLongTapCallBack_inner34;
    class _Delegate_Base_CallBack_inner35;
    template <class TClass> class _DelegateI_CallBack_inner35;
    class _DelegateS_CallBack_inner35;
    class _Delegate_Base_CallBack_inner36;
    template <class TClass> class _DelegateI_CallBack_inner36;
    class _DelegateS_CallBack_inner36;
    class _Delegate_Base_SelectableCallBack_inner37;
    template <class TClass> class _DelegateI_SelectableCallBack_inner37;
    class _DelegateS_SelectableCallBack_inner37;
    class _Delegate_Base_AnimCallBack_inner38;
    template <class TClass> class _DelegateI_AnimCallBack_inner38;
    class _DelegateS_AnimCallBack_inner38;
    class _Delegate_Base_AnimCallBack_inner39;
    template <class TClass> class _DelegateI_AnimCallBack_inner39;
    class _DelegateS_AnimCallBack_inner39;
    class _Delegate_Base_LimitCallBack_inner40;
    template <class TClass> class _DelegateI_LimitCallBack_inner40;
    class _DelegateS_LimitCallBack_inner40;
    class _Delegate_Base_DragCallBack_inner41;
    template <class TClass> class _DelegateI_DragCallBack_inner41;
    class _DelegateS_DragCallBack_inner41;
    class _Delegate_Base_DynamicCallBack_inner42;
    template <class TClass> class _DelegateI_DynamicCallBack_inner42;
    class _DelegateS_DynamicCallBack_inner42;
    class _Delegate_Base_ScrollBarCallBack_inner43;
    template <class TClass> class _DelegateI_ScrollBarCallBack_inner43;
    class _DelegateS_ScrollBarCallBack_inner43;
    class _Delegate_Base_AnimCallBack_inner44;
    template <class TClass> class _DelegateI_AnimCallBack_inner44;
    class _DelegateS_AnimCallBack_inner44;
    class _Delegate_Base_CallBack_inner45;
    template <class TClass> class _DelegateI_CallBack_inner45;
    class _DelegateS_CallBack_inner45;
    class _Delegate_Base_ScrollBarCallBack_inner46;
    template <class TClass> class _DelegateI_ScrollBarCallBack_inner46;
    class _DelegateS_ScrollBarCallBack_inner46;
    class _Delegate_Base_CallBack_inner47;
    template <class TClass> class _DelegateI_CallBack_inner47;
    class _DelegateS_CallBack_inner47;
    class _Delegate_Base_CallBack_inner48;
    template <class TClass> class _DelegateI_CallBack_inner48;
    class _DelegateS_CallBack_inner48;
    class _Delegate_Base_CallBack_inner49;
    template <class TClass> class _DelegateI_CallBack_inner49;
    class _DelegateS_CallBack_inner49;
    class _Delegate_Base_CallBack_inner50;
    template <class TClass> class _DelegateI_CallBack_inner50;
    class _DelegateS_CallBack_inner50;
    class _Delegate_Base_CallBack_inner51;
    template <class TClass> class _DelegateI_CallBack_inner51;
    class _DelegateS_CallBack_inner51;
    class CKLBException;
    class CKLBExceptionNotImplemented;
    class CKLBExceptionForbiddenMethod;
    class CKLBExceptionNullCppObject;
    class CKLBExceptionTooOld;
    class GameObject;
    class GameObjectFactory;
    class NativeManagement;
    class NodeIterator;
    class Element;
    class Container;
    class Selectable;
    class AnimationNode;
    struct Size;
    struct USize;
    struct FSize;
    class IClientRequest;
    class __FrameworkUtils;
    class WrapperReg;
    class CSAPP;
    class CSAsset;
    class CSBin;
    class CSData;
    class CSDB;
    class CSDebug;
    class CSEng;
    class CSFont;
    struct STextInfo_inner0;
    class CSGL;
    class CSKey;
    class CSLang;
    class CSMatrix;
    class CSVector_inner1;
    class CSRES;
    class CSSound;
    class CSSystem;
    struct SystemInfo_inner2;
    class CSUI;
    class CKLBAsyncLoader;
    class CKLBGenericTask;
    class CKLBIntervalTimer;
    class CKLBNetAPI;
    class CKLBStoreService;
    class CKLBTask;
    class CKLBUICanvas;
    class CKLBUIClip;
    class CKLBUIControl;
    class CKLBUIDebugItem;
    class CKLBUIDragIcon;
    struct Area_inner3;
    class CKLBUIForm;
    class CKLBUIFreeVertItem;
    class CKLBUIGroup;
    class CKLBUILabel;
    class CKLBUIList;
    class CKLBUIMoviePlayer;
    class CKLBUIMultiImgItem;
    class CKLBUIPieChart;
    class CKLBUIPolyline;
    class CKLBUIProgressBar;
    class CKLBUIRubberBand;
    class CKLBUIScale9;
    class AnimationInfo;
    class CKLBUIScore;
    class CKLBUIScrollBar;
    class CKLBUISimpleItem;
    class CKLBUISWFPlayer;
    class CKLBUITask;
    class Spline_inner4;
    class IntSpline_inner5;
    class IntPoint_inner6;
    class FloatSpline_inner7;
    class FloatPoint_inner8;
    class AnimSpline_inner9;
    class CKLBUITextInput;
    class CKLBUITouchPad;
    class CKLBUIVariableItem;
    class CKLBUIVirtualDoc;
    class CKLBUIWebArea;

}
namespace SampleGame {
    class Program;

}
